"""Test the flash age compositor."""
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2019 Satpy developers
#
# This file is part of satpy.
#
# satpy is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# satpy is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# satpy.  If not, see <http://www.gnu.org/licenses/>.


import datetime
import logging

import dask.array as da
import numpy as np
import pandas as pd
import pytest
import xarray as xr

from satpy.composites.lightning import LightningTimeCompositor


@pytest.fixture
def lgr_sample_dict():
    """Get a dictionary for a sample LGR dataframe."""
    # generated by loading a scene with the li_l2_nc reader, then
    # to_dataframe on a dataarray and to_dict on that dataframe.  Dict
    # retains more metadata than CSV.

    return {"index": [(0, 0),
      (0, 1),
      (0, 2),
      (0, 3),
      (0, 4),
      (0, 5),
      (0, 6),
      (0, 7),
      (0, 8),
      (0, 9),
      (0, 10),
      (0, 11),
      (0, 12),
      (0, 13),
      (0, 14),
      (0, 15),
      (0, 16),
      (0, 17),
      (0, 18),
      (0, 19),
      (0, 20),
      (0, 21),
      (0, 22)],
     "columns": ["group_id", "flash_id", "latitude", "longitude", "group_time"],
     "data": [[718302742,
       99630775,
       11.115900039672852,
       -5.953500270843506,
       pd.Timestamp("2026-05-04 16:27:01.136800")],
      [718302743,
       99630775,
       11.115900039672852,
       -5.9832000732421875,
       pd.Timestamp("2026-05-04 16:27:01.139799936")],
      [718302744,
       99630775,
       11.129400253295898,
       -5.996700286865234,
       pd.Timestamp("2026-05-04 16:27:01.140800")],
      [718302745,
       99630775,
       11.13479995727539,
       -6.002099990844727,
       pd.Timestamp("2026-05-04 16:27:01.141800064")],
      [718302746,
       99630775,
       11.115900039672852,
       -5.9832000732421875,
       pd.Timestamp("2026-05-04 16:27:01.142800")],
      [718302747,
       99630775,
       10.999800682067871,
       -6.037199974060059,
       pd.Timestamp("2026-05-04 16:27:01.147799936")],
      [718302748,
       99630776,
       11.469600677490234,
       -5.902200222015381,
       pd.Timestamp("2026-05-04 16:27:01.382800")],
      [718302749,
       99630776,
       11.46150016784668,
       -5.894100189208984,
       pd.Timestamp("2026-05-04 16:27:01.383800064")],
      [718302750,
       99630776,
       11.469600677490234,
       -5.902200222015381,
       pd.Timestamp("2026-05-04 16:27:01.384800")],
      [718302751,
       99630776,
       11.469600677490234,
       -5.886000156402588,
       pd.Timestamp("2026-05-04 16:27:01.390800")],
      [718302752,
       99630776,
       11.469600677490234,
       -5.8805999755859375,
       pd.Timestamp("2026-05-04 16:27:01.391800064")],
      [718302753,
       99630776,
       11.458800315856934,
       -5.891400337219238,
       pd.Timestamp("2026-05-04 16:27:01.393800064")],
      [718302754,
       99630776,
       11.483099937438965,
       -5.888700008392334,
       pd.Timestamp("2026-05-04 16:27:01.407799936")],
      [718302755,
       99630776,
       11.483099937438965,
       -5.899500370025635,
       pd.Timestamp("2026-05-04 16:27:01.409800064")],
      [718302756,
       99630776,
       11.469600677490234,
       -5.902200222015381,
       pd.Timestamp("2026-05-04 16:27:01.423799936")],
      [718302757,
       99630776,
       11.480400085449219,
       -5.891400337219238,
       pd.Timestamp("2026-05-04 16:27:01.424800")],
      [718302758,
       99630776,
       11.485800743103027,
       -5.886000156402588,
       pd.Timestamp("2026-05-04 16:27:01.429800064")],
      [718302759,
       99630776,
       11.499300003051758,
       -5.894100189208984,
       pd.Timestamp("2026-05-04 16:27:01.439800064")],
      [718302760,
       99630776,
       11.499300003051758,
       -5.894100189208984,
       pd.Timestamp("2026-05-04 16:27:01.440800")],
      [718302761,
       99630776,
       11.501999855041504,
       -5.891400337219238,
       pd.Timestamp("2026-05-04 16:27:01.441799936")],
      [718302762,
       99630776,
       11.499300003051758,
       -5.875200271606445,
       pd.Timestamp("2026-05-04 16:27:01.664800")],
      [718302770,
       99630784,
       10.470600128173828,
       -6.350399971008301,
       pd.Timestamp("2026-05-04 16:27:02.225800064")],
      [718302771,
       99630784,
       10.527299880981445,
       -6.2910003662109375,
       pd.Timestamp("2026-05-04 16:27:02.225800064")]],
     "index_names": ["auxiliary_dataset", "groups"],
     "column_names": [None]}


@pytest.fixture
def lfl_sample_dict():
    """Return dict for sample LFL data."""
    return {"flash_id": {(0, 0, 0): 99630775, (0, 1, 0): 99630776, (0, 2, 0):
                        99630784}}

@pytest.fixture
def lgr_sample(lgr_sample_dict):
    """Return a small sample of LGR data as a DataFrame."""
    df = pd.DataFrame.from_dict(lgr_sample_dict, orient="tight")
    return df.astype({
        "group_id": "uint32",
        "flash_id": "uint32",
        "latitude": "float32",
        "longitude": "float32"})

@pytest.fixture
def lfl_sample(lfl_sample_dict):
    """Return a small sample of LFL data as a DataFrame."""
    return pd.DataFrame.from_dict(lfl_sample_dict).astype({"flash_id": "uint32"})

def test_flash_age_compositor():
    """Test the flash_age compsitor by comparing two xarrays object."""
    comp = LightningTimeCompositor("flash_age",prerequisites=["flash_time"],
                                   standard_name="lightning_time",
                                   time_range=60,
                                   reference_time="end_time")
    attrs_flash_age = {"variable_name": "flash_time","name": "flash_time",
                       "start_time": datetime.datetime(2024, 8, 1, 10, 50, 0),
                       "end_time": datetime.datetime(2024, 8, 1, 11, 0, 0),"reader": "li_l2_nc"}
    flash_age_value = da.array(["2024-08-01T09:00:00",
            "2024-08-01T10:00:00", "2024-08-01T10:30:00","2024-08-01T11:00:00"], dtype="datetime64[ns]")
    flash_age = xr.DataArray(
        flash_age_value,
        dims=["y"],
        coords={
            "crs": "8B +proj=longlat +ellps=WGS84 +type=crs"},
        attrs = attrs_flash_age,
        name="flash_time")
    res = comp([flash_age])
    expected_attrs = {"variable_name": "flash_time","name": "lightning_time",
                       "start_time": datetime.datetime(2024, 8, 1, 10, 50, 0),
                       "end_time": datetime.datetime(2024, 8, 1, 11, 0, 0),"reader": "li_l2_nc",
                       "standard_name": "lightning_time"
                       }
    expected_array = xr.DataArray(da.array([np.nan, 0.0,0.5,1.0]),
                                  dims=["y"],
                                  coords={
                                      "crs": "8B +proj=longlat +ellps=WGS84 +type=crs"},
                                  attrs = expected_attrs,
                                  name="flash_time")
    xr.testing.assert_equal(res,expected_array)

def test_empty_array_error(caplog):
    """Test when the filtered array is empty."""
    comp = LightningTimeCompositor("flash_age",prerequisites=["flash_time"],
                                   standard_name="lightning_time",
                                   time_range=60,
                                   reference_time="end_time")
    attrs_flash_age = {"variable_name": "flash_time","name": "flash_time",
                       "start_time": np.datetime64(datetime.datetime(2024, 8, 1, 10, 0, 0)),
                       "end_time": datetime.datetime(2024, 8, 1, 11, 0, 0),
                       "reader": "li_l2_nc"}
    flash_age_value = da.array(["2024-08-01T09:00:00"], dtype="datetime64[ns]")
    flash_age = xr.DataArray(flash_age_value,
                             dims=["y"],
                             coords={
                                 "crs": "8B +proj=longlat +ellps=WGS84 +type=crs"},
                             attrs = attrs_flash_age,
                             name="flash_time")
    with caplog.at_level(logging.WARNING):
        _ = comp([flash_age])
    # Assert that the log contains the expected warning message
    assert "All the flash_age events happened before" in caplog.text

def test_update_missing_metadata():
    """Test the _update_missing_metadata method."""
    existing_attrs = {
        "standard_name": "lightning_event_time",
        "time_range": 30
    }

    # New metadata to be merged
    new_attrs = {
        "standard_name": None,  # Should not overwrite since it's None
        "reference_time": "2023-09-20T00:00:00Z",  # Should be added
        "units": "seconds"  # Should be added
    }

    # Expected result after merging
    expected_attrs = {
        "standard_name": "lightning_event_time",  # Should remain the same
        "time_range": 30,  # Should remain the same
        "reference_time": "2023-09-20T00:00:00Z",  # Should be added
        "units": "seconds"  # Should be added
    }

    # Call the static method
    LightningTimeCompositor._update_missing_metadata(existing_attrs, new_attrs)

    # Assert the final state of existing_attrs is as expected
    assert existing_attrs == expected_attrs

def test_vectorscene_load_flash_geometry(lgr_sample, lfl_sample):
    """Test we can get flash geometry from a VectorScene."""
    raise NotImplementedError()
