"""Test the flash age compositor."""
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2019 Satpy developers
#
# This file is part of satpy.
#
# satpy is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# satpy is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# satpy.  If not, see <http://www.gnu.org/licenses/>.


import datetime
import logging

import dask.array as da
import numpy as np
import pytest
import xarray as xr

from satpy.composites.lightning import LightningTimeCompositor


@pytest.fixture
def lgr_sample_dict():
    """Get a dictionary for a sample LGR dataset."""
    # generated by loading a scene with the li_l2_nc reader, then
    # to_dataframe on a dataarray and to_dict on that dataframe.  Dict
    # retains more metadata than CSV.

    return {"coords": {},
 "attrs": {"title": "",
  "summary": "",
  "keywords": "",
  "keywords_vocabulary": "",
  "subtype": "",
  "component1": "",
  "component2": "",
  "component3": "",
  "algorithm_version": "",
  "format_version": "",
  "special_compression": "",
  "subsetting": "",
  "runtime_data": "",
  "parent_data": "",
  "group_tag": "",
  "subsettable_groups": "",
  "subsettable_groups_present": "",
  "mtg_name": "",
  "alternative_name": "",
  "purpose": "",
  "id": "",
  "naming_authority": "EUMETSAT",
  "cdm_datatype": "",
  "geospatial_lat_min": -82.0,
  "geospatial_lat_max": 82.0,
  "geospatial_lon_min": -82.0,
  "geospatial_lon_max": 82.0,
  "platform": "MTI1",
  "creator_url": "www.eumetsat.int",
  "linked_data": "",
  "project": "MTG",
  "data_designator": "IMG+SAT",
  "time_coverage_resolution": "",
  "release_version": "Original",
  "coverage": "FD",
  "history": "Original generated version",
  "baseline_version": "",
  "date_time_position": "YYYYMMDDhhmmss",
  "license": "",
  "format": "NC4E",
  "processing_mode": "N",
  "creator_type": "institution",
  "comment": "None",
  "references": "www.eumetsat.int",
  "standard_name_vocabulary": "CF Standard Name Table v27",
  "time_position": "hhmmss",
  "location_indicator": "XX-EUMETSAT-Darmstadt",
  "instrument_configuration_id_version": "0",
  "facility_or_tool": "L2PF",
  "instrument_configuration_id": "0",
  "Conventions": "CF-1.7",
  "creator_institution": "EUMETSAT",
  "processor_version": "",
  "creator_name": "",
  "creator_email": "ops@eumetsat.int",
  "institution": "EUMETSAT",
  "processing_level": "2",
  "source": "LI",
  "data_source": "LI",
  "repeat_cycle_in_day": "0099",
  "count_in_repeat_cycle": "0043",
  "processed_count_in_repeat_cycle": "0043",
  "date_created": "20260504162742",
  "time_coverage_start": "20260504162700",
  "time_coverage_end": "20260504162710",
  "environment": "OPE",
  "type": "LGR",
  "product_id": "LI-2-LGR-x-FD",
  "time_coverage_duration": "10",
  "disposition_mode": "O"},
 "dims": {"auxiliary_dataset": 1, "groups": 23},
 "data_vars": {"auxiliary_dataset_identifier": {"dims": ("auxiliary_dataset",),
   "attrs": {"long_name": "Auxiliary dataset identifier",
    "title": "Identifier of auxiliary dataset or type of auxiliary dataset used to produce this product"},
   "data": ["CM__L2-PROC_MTI1+LI_20250122000000_static.nc"]},
  "auxiliary_dataset_status": {"dims": ("auxiliary_dataset",),
   "attrs": {"long_name": "Status of auxiliary dataset",
    "meaning": "0 = OK, 1 = out_of_validity_time, 2 = not_available"},
   "data": [0]},
  "l1b_missing_warning": {"dims": (),
   "attrs": {"long_name": "Expected L1b inputs missing"},
   "data": 0},
  "l1b_geolocation_warning": {"dims": (),
   "attrs": {"long_name": "L1b event geolocation warning"},
   "data": 0},
  "l1b_radiometric_warning": {"dims": (),
   "attrs": {"long_name": "L1b event radiometric warning"},
   "data": 0},
  "group_time": {"dims": ("groups",),
   "attrs": {"long_name": "Start time of integration frame",
    "standard_name": "time",
    "precision": "0.001",
    "time_standard": "UTC"},
   "data": [datetime.datetime(2026, 5, 4, 16, 27, 1, 136800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 139799),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 140800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 141800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 142800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 147799),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 382800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 383800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 384800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 390800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 391800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 393800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 407799),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 409800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 423799),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 424800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 429800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 439800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 440800),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 441799),
    datetime.datetime(2026, 5, 4, 16, 27, 1, 664800),
    datetime.datetime(2026, 5, 4, 16, 27, 2, 225800),
    datetime.datetime(2026, 5, 4, 16, 27, 2, 225800)]},
  "latitude": {"dims": ("groups",),
   "attrs": {"long_name": "Latitude of group",
    "units": "degrees_north",
    "standard_name": "latitude"},
   "data": [11.115900039672852,
    11.115900039672852,
    11.129400253295898,
    11.13479995727539,
    11.115900039672852,
    10.999800682067871,
    11.469600677490234,
    11.46150016784668,
    11.469600677490234,
    11.469600677490234,
    11.469600677490234,
    11.458800315856934,
    11.483099937438965,
    11.483099937438965,
    11.469600677490234,
    11.480400085449219,
    11.485800743103027,
    11.499300003051758,
    11.499300003051758,
    11.501999855041504,
    11.499300003051758,
    10.470600128173828,
    10.527299880981445]},
  "longitude": {"dims": ("groups",),
   "attrs": {"long_name": "Longitude of group",
    "units": "degrees_east",
    "standard_name": "longitude"},
   "data": [-5.953500270843506,
    -5.9832000732421875,
    -5.996700286865234,
    -6.002099990844727,
    -5.9832000732421875,
    -6.037199974060059,
    -5.902200222015381,
    -5.894100189208984,
    -5.902200222015381,
    -5.886000156402588,
    -5.8805999755859375,
    -5.891400337219238,
    -5.888700008392334,
    -5.899500370025635,
    -5.902200222015381,
    -5.891400337219238,
    -5.886000156402588,
    -5.894100189208984,
    -5.894100189208984,
    -5.891400337219238,
    -5.875200271606445,
    -6.350399971008301,
    -6.2910003662109375]},
  "radiance": {"dims": ("groups",),
   "attrs": {"long_name": "Radiance of group", "units": "mW.m-2.sr-1"},
   "data": [3.5,
    8.0,
    34.5,
    28.0,
    9.0,
    7.0,
    4.0,
    16.5,
    4.0,
    14.0,
    24.0,
    11.0,
    8.0,
    20.5,
    3.5,
    9.0,
    11.5,
    13.0,
    13.0,
    21.5,
    3.5,
    3.5,
    4.0]},
  "group_id": {"dims": ("groups",),
   "attrs": {"long_name": "LI L2 Group IDs"},
   "data": [718302742,
    718302743,
    718302744,
    718302745,
    718302746,
    718302747,
    718302748,
    718302749,
    718302750,
    718302751,
    718302752,
    718302753,
    718302754,
    718302755,
    718302756,
    718302757,
    718302758,
    718302759,
    718302760,
    718302761,
    718302762,
    718302770,
    718302771]},
  "flash_id": {"dims": ("groups",),
   "attrs": {"long_name": "ID of associated LI L2 Flash object with each group"},
   "data": [99630775,
    99630775,
    99630775,
    99630775,
    99630775,
    99630775,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630776,
    99630784,
    99630784]},
  "number_of_events": {"dims": ("groups",),
   "attrs": {"long_name": "Number of events in each group"},
   "data": [1,
    2,
    6,
    5,
    2,
    2,
    1,
    4,
    1,
    3,
    4,
    2,
    2,
    3,
    1,
    2,
    2,
    3,
    3,
    3,
    1,
    1,
    1]},
  "group_filter_qa": {"dims": ("groups",),
   "attrs": {"long_name": "L2 filtered group quality assurance value"},
   "data": [0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0]}}}


@pytest.fixture
def lgr_sample_xr(lgr_sample_dict):
    """Return a small sample of LGR data as an xarray.Dataset."""
    return xr.Dataset.from_dict(lgr_sample_dict)


@pytest.fixture
def lgr_sample_file(lgr_sample_xr, tmp_path):
    """Return a small sample LGR file."""
    fn = (tmp_path / "W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+LI-2-LGR--FD--"
                     "CHK-BODY---NC4E_C_EUMT_21260504162742_L2PF_OPE_"
                     "20260504162700_20260504162710_N__T_0099_0043.nc")
    lgr_sample_xr.to_netcdf(fn)
    return fn


def test_flash_age_compositor():
    """Test the flash_age compsitor by comparing two xarrays object."""
    comp = LightningTimeCompositor("flash_age",prerequisites=["flash_time"],
                                   standard_name="lightning_time",
                                   time_range=60,
                                   reference_time="end_time")
    attrs_flash_age = {"variable_name": "flash_time","name": "flash_time",
                       "start_time": datetime.datetime(2024, 8, 1, 10, 50, 0),
                       "end_time": datetime.datetime(2024, 8, 1, 11, 0, 0),"reader": "li_l2_nc"}
    flash_age_value = da.array(["2024-08-01T09:00:00",
            "2024-08-01T10:00:00", "2024-08-01T10:30:00","2024-08-01T11:00:00"], dtype="datetime64[ns]")
    flash_age = xr.DataArray(
        flash_age_value,
        dims=["y"],
        coords={
            "crs": "8B +proj=longlat +ellps=WGS84 +type=crs"},
        attrs = attrs_flash_age,
        name="flash_time")
    res = comp([flash_age])
    expected_attrs = {"variable_name": "flash_time","name": "lightning_time",
                       "start_time": datetime.datetime(2024, 8, 1, 10, 50, 0),
                       "end_time": datetime.datetime(2024, 8, 1, 11, 0, 0),"reader": "li_l2_nc",
                       "standard_name": "lightning_time"
                       }
    expected_array = xr.DataArray(da.array([np.nan, 0.0,0.5,1.0]),
                                  dims=["y"],
                                  coords={
                                      "crs": "8B +proj=longlat +ellps=WGS84 +type=crs"},
                                  attrs = expected_attrs,
                                  name="flash_time")
    xr.testing.assert_equal(res,expected_array)


def test_empty_array_error(caplog):
    """Test when the filtered array is empty."""
    comp = LightningTimeCompositor("flash_age",prerequisites=["flash_time"],
                                   standard_name="lightning_time",
                                   time_range=60,
                                   reference_time="end_time")
    attrs_flash_age = {"variable_name": "flash_time","name": "flash_time",
                       "start_time": np.datetime64(datetime.datetime(2024, 8, 1, 10, 0, 0)),
                       "end_time": datetime.datetime(2024, 8, 1, 11, 0, 0),
                       "reader": "li_l2_nc"}
    flash_age_value = da.array(["2024-08-01T09:00:00"], dtype="datetime64[ns]")
    flash_age = xr.DataArray(flash_age_value,
                             dims=["y"],
                             coords={
                                 "crs": "8B +proj=longlat +ellps=WGS84 +type=crs"},
                             attrs = attrs_flash_age,
                             name="flash_time")
    with caplog.at_level(logging.WARNING):
        _ = comp([flash_age])
    # Assert that the log contains the expected warning message
    assert "All the flash_age events happened before" in caplog.text


def test_update_missing_metadata():
    """Test the _update_missing_metadata method."""
    existing_attrs = {
        "standard_name": "lightning_event_time",
        "time_range": 30
    }

    # New metadata to be merged
    new_attrs = {
        "standard_name": None,  # Should not overwrite since it's None
        "reference_time": "2023-09-20T00:00:00Z",  # Should be added
        "units": "seconds"  # Should be added
    }

    # Expected result after merging
    expected_attrs = {
        "standard_name": "lightning_event_time",  # Should remain the same
        "time_range": 30,  # Should remain the same
        "reference_time": "2023-09-20T00:00:00Z",  # Should be added
        "units": "seconds"  # Should be added
    }

    # Call the static method
    LightningTimeCompositor._update_missing_metadata(existing_attrs, new_attrs)

    # Assert the final state of existing_attrs is as expected
    assert existing_attrs == expected_attrs


def test_vectorscene_load_flash_geometry(lgr_sample_file):
    """Test we can get flash geometry from a VectorScene."""
    from satpy.vectorscene import VectorScene
    vs = VectorScene(filenames=[lgr_sample_file],
                     reader=["li_l2_nc"])
    vs.load(["acc_flash_geometry"])
    raise NotImplementedError()
